### ISSUE TITLE
您好，安装您的插件时，出现了如下的错误

### ISSUE THREAD

**Issue by dongsongshan** [wfzong/strapi-wechat-miniprogram-auth#1]
debug: ⛔️ Server wasn't able to start properly.
[2022-12-02 17:35:46.396] error: alter table `strapi-wechat-miniprogram-auth_wechat-credential` add constraint `strapi-wechat-miniprogram-auth_wechat-credential_created_by_id_fk` foreign key (`created_by_id`) references `admin_users` (`id`) on delete SET NULL - ER_TOO_LONG_IDENT: Identifier name 'strapi-wechat-miniprogram-auth_wechat-credential_created_by_id_fk' is too long
Error: ER_TOO_LONG_IDENT: Identifier name 'strapi-wechat-miniprogram-auth_wechat-credential_created_by_id_fk' is too long

**Comment by wfzong** [comment]
> 

你好，请提供一下node版本和strapi版本

**Comment by dongsongshan** [comment]
node版本16.14.2
strapi版本4.4.6

**Comment by wfzong** [comment]
> node版本16.14.2
> strapi版本4.4.6

你好，我刚刚在windows 11系统的机器上，node 16.14.2, strapi 4.4.6版本，重新安装、测试了一下插件，都可以正常操作。
麻烦能不能提供一下更多的细节？

或者加我微信：icewfz

**Comment by lionof** [comment]
我也遇到了同样的问题
数据库版本：mysql 5.7.38 （远程部署于CentOS Stream 8 x86_64）
node.js版本：v16.16.0
操作系统：windows 10

package.json
{ "name": "hlf-api", "private": true, "version": "0.1.0", "description": "A Strapi application", "scripts": { "develop": "strapi develop", "start": "strapi start", "build": "strapi build", "strapi": "strapi" }, "devDependencies": {}, "dependencies": { "@strapi/plugin-i18n": "4.5.3", "@strapi/plugin-users-permissions": "4.5.3", "@strapi/strapi": "4.5.3", "mysql": "2.18.1", "strapi-wechat-miniprogram-auth": "^0.0.4" }, "author": { "name": "A Strapi developer" }, "strapi": { "uuid": "46326733-a981-4f8d-bfab-60991ee5f84d" }, "engines": { "node": ">=14.19.1 <=18.x.x", "npm": ">=6.0.0" }, "license": "MIT" }
