### ISSUE TITLE
我装了插件，点击按钮进去页面空白的

### ISSUE THREAD

**Issue by bigoctopus8** [wfzong/strapi-wechat-miniprogram-auth#3]
![WX20221209-134203@2x](https://user-images.githubusercontent.com/19276668/206632589-f3fc157b-a7fa-4eb7-a712-b80243bfafe9.png)

点击了以后进去页面空白，没有配置

**Comment by wfzong** [comment]
请提供一下运行环境
系统：
node版本：
strapi版本：
用的什么数据库：
