### ISSUE TITLE
404无法访问http://localhost/strapi-wechat-miniprogram-auth/login

### ISSUE THREAD

**Issue by akacclin** [wfzong/strapi-wechat-miniprogram-auth#4]
node及strapi均是最新的稳定版，数据库是默认的，按照readme完整配置了，访问http://localhost/strapi-wechat-miniprogram-auth/login返回code为404，有可能是什么原因造成的呢？

**Comment by wfzong** [comment]
请给出具体环境参数，我测试一下

系统：
node版本：
strapi版本：
用的什么数据库：

**Comment by wfzong** [comment]
请注意请类型，是 post 请求，不是 get 请求。

**Comment by akacclin** [comment]
抱歉回复晚了。我刚重新建了个项目跑了一次是能够正确获取token的，问题应该是出在我的代码上，感谢你的回复和对社区的贡献！

**Comment by akacclin** [comment]
找到问题了抱歉，是我的appId绑定错了，和程序不匹配
