### ISSUE TITLE
v4.9.1 安装插件后在后台找不到配置项?

### ISSUE THREAD

**Issue by mircool** [wfzong/strapi-wechat-miniprogram-auth#7]
是不是版本的原因,插件安装成功后台却不显示

"STEP 3
Config the WeChat AppID and AppSecret.
Go to the Strapi Dashboard, and change to the PLUGINS -> WeChat Mini Program Authenticator, input the AppID,AppSecret and save it."

**Comment by wfzong** [comment]
可以试试npm run build一下，然后再启动项目

**Comment by mircool** [comment]
解决了,歪瑞双Q
