### ISSUE TITLE
How to get code to login.

### ISSUE THREAD

**Issue by MhmodTayel** [wfzong/strapi-wechat-miniprogram-auth#8]
I want to add this plugin to my application to enable login with WeChat. The scenario I have in mind is when a user clicks 'Register with WeChat,' they will be redirected to a screen where they can scan a QR code with the WeChat application. Then, the page will redirect them to the callback URL with the code to log in. The question is, how can I get this link to generate the QR code?

I found this link: https://open.weixin.qq.com/connect/qrconnect?appid=APPID&redirect_uri=REDIRECT_URL&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect

I have an official account on http://mp.weixin.qq.com/, and I configured the redirect URL, but I always get this error: 'Scope parameter error' or 'No Scope permission.'

**Comment by wfzong** [comment]
This package is not a WeChat plugin, it's a WeChat MiniProgram auth plugin.

**Comment by MhmodTayel** [comment]
@wfzong could you please provide my with an example to use this plugin in a reactJs project and what credentials I need
